name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./bot          # bot folder ကို အဓိက context အဖြစ် သတ်မှတ်မယ်
          file: ./bot/Dockerfile  # Dockerfile ရှိတဲ့နေရာ
          push: true
          tags: kyawpaingzaw/telegram-session-store:latest
